clean build before making deb, preinst removed

diff --git a/make_deb b/make_deb
--- a/make_deb
+++ b/make_deb
@@ -66,7 +66,7 @@ done
 
 # If the architecture has not been defined, then the script is complete
 if [ "$(dpkg --print-architecture)" != "armhf" ]; then
-	echo "Package building is only supported on arm* architecture!!"
+	echo "Package building is only supported on armhf architecture!!"
 	exit 0
 fi
 
@@ -97,38 +97,28 @@ if [ ! -L "${BUILD_ROOT}" -a ! -d "${BUILD_ROOT}" ]; then
     mkdir -p "${BUILD_ROOT}"
 fi
 
-# Check plugin has been built
-if [ ! -d "${GIT_ROOT}/build" ]; then
-    echo "Warning: ./build directory not found."
-    echo "Building plugin ${plugin_name} first."
-    # Check FOGLAMP_ROOT
-    if [ -z ${FOGLAMP_ROOT+x} ]; then
-        # Set FOGLAMP_ROOT as the default directory
-        FOGLAMP_ROOT="/usr/local/foglamp"
-        export FOGLAMP_ROOT
-    fi
 
-    # Check if the default directory exists
-    if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
-        logger -p local0.err -t "foglamp.script.foglamp" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
-        echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
-        echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
-        echo "Specify the base directory for FogLAMP and set the variable with:"
-        echo "export FOGLAMP_ROOT=<basedir>"
-        exit 1
-    fi
 
-    # Check/set LD_LIBRARY_PATH
-    libPathSet=0
-    libdir=${FOGLAMP_ROOT}/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
-    libdir=${FOGLAMP_ROOT}/cmake_build/C/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
-    [ "$libPathSet" -eq "0" ] && echo "Unable to set/update LD_LIBRARY_PATH to include path of Foglamp shared libraries: check whether ${FOGLAMP_ROOT}/lib or ${FOGLAMP_ROOT}/cmake_build/C/lib exists" && exit 1
-
-    # Build wiringpi first
-    cd /tmp; git clone git://git.drogon.net/wiringPi; cd wiringPi; ./build; cd ${GIT_ROOT}
-    mkdir ./build; cd ./build; cmake ..; make; cd ..
-    #exit 1
+# Check if the default directory exists
+if [[ ! -d "${FOGLAMP_ROOT}" ]]; then
+    logger -p local0.err -t "foglamp.script.foglamp" "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "FogLAMP cannot be executed: ${FOGLAMP_ROOT} is not a valid directory."
+    echo "Create the enviroment variable FOGLAMP_ROOT before using FogLAMP."
+    echo "Specify the base directory for FogLAMP and set the variable with:"
+    echo "export FOGLAMP_ROOT=<basedir>"
+    exit 1
 fi
+
+# Check/set LD_LIBRARY_PATH
+libPathSet=0
+libdir=${FOGLAMP_ROOT}/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
+libdir=${FOGLAMP_ROOT}/cmake_build/C/lib; [ -d ${libdir} ] && LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | sed "s|${libdir}||g") && export LD_LIBRARY_PATH=${libdir}:${LD_LIBRARY_PATH} && libPathSet=1
+[ "$libPathSet" -eq "0" ] && echo "Unable to set/update LD_LIBRARY_PATH to include path of Foglamp shared libraries: check whether ${FOGLAMP_ROOT}/lib or ${FOGLAMP_ROOT}/cmake_build/C/lib exists" && exit 1
+
+# Build wiringpi first
+cd /tmp; rm -rf wiringPi; git clone git://git.drogon.net/wiringPi; cd wiringPi; ./build; cd ${GIT_ROOT}
+rm -rf build; mkdir ./build; cd ./build; cmake ..; make; cd ..
+
 
 cd "${BUILD_ROOT}"
 existing_pkgs=`find . -maxdepth 1 -name "${package_name}.????" | wc -l`
